/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bms.HowToConnect;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author User
 */
public class SelectedCustomer extends javax.swing.JFrame {

    /**
     * Creates new form SelectedCustomer
     */
    public SelectedCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustomerSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomer = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustomerSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCustomerSearch.setBorder(null);
        txtCustomerSearch.setOpaque(false);
        txtCustomerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerSearchKeyTyped(evt);
            }
        });
        getContentPane().add(txtCustomerSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 48));

        listCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 158, 250));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blur1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerSearchKeyTyped
        // TODO add your handling code here:
        String sk = txtCustomerSearch.getText().trim();
        DefaultListModel dlm = new DefaultListModel();
        HowToConnect connect = new HowToConnect();
        String sql = "select distinct F_name, L_name from customer where F_name like '%" + sk + "%' or L_name like '"+ sk +"'";
        try {
            connect.systemConnection();
            connect.res = connect.stat.executeQuery(sql);

            while (connect.res.next()) {
                String pName = connect.res.getString(1);
                String lName = connect.res.getString(2);
                dlm.addElement(pName +" "+ lName);
                listCustomer.setModel(dlm);
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_txtCustomerSearchKeyTyped

    private void listCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCustomerMouseClicked
        // TODO add your handling code here:
        int index = listCustomer.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        String s = (String) listCustomer.getSelectedValue();
        System.out.println("Value Selected: " + s);
        
        new Home(s).setVisible(true);
            setVisible(false);
            dispose();
        
        
    }//GEN-LAST:event_listCustomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectedCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listCustomer;
    private javax.swing.JTextField txtCustomerSearch;
    // End of variables declaration//GEN-END:variables
}
