/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bms.connectionClass;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Supplier extends javax.swing.JInternalFrame {

    private DefaultTableModel model;

    /**
     * Creates new form Supplier
     */
    public Supplier() throws Exception {
        initComponents();
        showSupplierTable();
    }

    public void showSupplierTable() throws Exception {
        connectionClass showSupplier = new connectionClass();
        showSupplier.connect();
        try {
            showSupplier.systemConnection();
            showSupplier.rs = showSupplier.stmt.executeQuery("select * from supplier");
            while (showSupplier.rs.next()) {
                int id = showSupplier.rs.getInt(1);
                String sName = showSupplier.rs.getString(2);
                int tele = showSupplier.rs.getInt(3);
                String address = showSupplier.rs.getString(4);
                int accNum = showSupplier.rs.getInt(5);
                System.out.println(id + " " + sName + " " + tele + " " + address +" "+accNum);
                Object[] content = {id, sName, tele, address,accNum};
                model = (DefaultTableModel) tblSupplier.getModel();
                model.addRow(content);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSupplier.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Number", "Mobil", "Acc_Number"
            }
        ));
        tblSupplier.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tblSupplier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1010, 450));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("New Supplier");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blur2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    // End of variables declaration//GEN-END:variables
}
